# Single file config example

# Required - Unique id. Used to find/terminate the iterm window.
#   Use different ids if you wahave different projects
id = "my-project-local-dev"
# Working directory for all sessions.
# If unset, assumes the current working directory.
directory = "~/code/saas-control-plane/"

# Must create a section called `sessions`
[sessions]

# `sessions.<name>` defines an iterm session.
[sessions.setup]
# `script` - the script to run.
#   Use a script when you want to the tool to wait until the commands are all done.
script = '''
sleep 5
echo 'Setup is done'
'''

[sessions.server]
# `depends_on` - a list of dependent sessions.
#    This session will not start until these other sessions have completed.
#    Remember that the tool only waits for `script` scripts to complete.
depends_on = ["sessions.setup"]
# `inject` - inject commands into the session, as if you had typed them.
#    The tool executes these but does not wait for them to complete.
#    This is useful if you want to manually press up-arrow to re-run commands.
inject = '''
echo 'This is where the server would start'
'''

[sessions.worker]
depends_on = ["sessions.setup"]
inject = '''
echo 'This is where the worker would start'
'''

